In [2]:
import pandas as pd
df=pd.read_csv('labeled_data.csv')
df.head()

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [8]:
x=df[['hate_speech','offensive_language']]
y=df['class']

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
X = df['tweet']

In [11]:
vectorizer = TfidfVectorizer()

In [12]:
X_vectorized = vectorizer.fit_transform(X)

In [13]:
print(X_vectorized.shape)

(24783, 35852)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    df['class'],
    test_size=0.2,
    random_state=42
)

In [16]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 259472 stored elements and shape (19826, 35852)>

In [17]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 64586 stored elements and shape (4957, 35852)>

In [19]:
y_train

15272    0
9351     2
20323    1
3638     1
20579    1
        ..
21575    2
5390     1
860      1
15795    1
23654    1
Name: class, Length: 19826, dtype: int64

In [20]:
y_test

2281     1
15914    1
18943    2
16407    1
13326    1
        ..
3310     0
22759    1
21953    1
9056     1
13246    1
Name: class, Length: 4957, dtype: int64

In [21]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [22]:
clf.predict(X_test)

array([0.93753925, 0.9484256 , 1.22029191, ..., 0.88696094, 0.88810901,
       1.05605202])

In [23]:
y_test

2281     1
15914    1
18943    2
16407    1
13326    1
        ..
3310     0
22759    1
21953    1
9056     1
13246    1
Name: class, Length: 4957, dtype: int64

In [24]:
clf.score(X_test,y_test)

-1.6657043558295297

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=10)
X_test

13665         Only basic bitches workout at planet fitness
6754     @nedrock83 don't tell what the fuck to "stop" ...
6417     @kieffer_jason How u going to talk shit from a...
10324    I gave my aunt my tupac greatest hits CD , tha...
4265              @NexusAltase Fuck her right in the pussy
                               ...
1422     &#8220;@MomMeMustHaves: MMMH Daily is out! htt...
5467     @adorianloveee man fuck this bitch http://t.co...
10169    I definitely cant FW a nigga that associates h...
15265    RT @FuckTraVonn: @TropicalKyle @wendella_ one ...
21206                                  Stupid fucking cunt
Name: tweet, Length: 7435, dtype: object